#!/usr/bin/env python3

import os
from sys import platform as _platform

def clearScreen(UNIX):
	if UNIX == 0:
		os.system("clear")

def checkOs():
	if _platform == "linux" or _platform == "linux2":
		return 0
